import type { CameraManifest } from '../types';
import {
  cameraFilterTileJsonUrl,
  cameraManifestUrl,
  loadCameraTileJson,
  type CameraTileCountry,
  type CameraTileJson,
} from './cameraTilesService';

const cached = new Map<CameraTileCountry, CameraManifest>();
const inFlight = new Map<CameraTileCountry, Promise<CameraManifest>>();

function assertManifestShape(data: unknown): asserts data is CameraManifest {
  const m = data as CameraManifest;
  if (
    !m ||
    !Array.isArray(m.brands) ||
    !Array.isArray(m.operators) ||
    !Array.isArray(m.zones) ||
    !Array.isArray(m.mounts)
  ) {
    throw new Error('Malformed camera manifest');
  }
}

/** Cache-busting query param: the CDN keys on the full URL, so a unique
 *  param pulls the origin copy past any stale edge entry. */
const bust = (url: string) => `${url}${url.includes('?') ? '&' : '?'}fresh=${Date.now()}`;

interface CompanionRequest {
  url: string;
  init?: RequestInit;
}

/**
 * Where to fetch a tileset companion document from. The primary host's
 * camera TileJSON names build-pinned companions (immutable, and coherent
 * with the tileset by construction) — use those when present. Otherwise the
 * unversioned alias on the active host, which changes hourly and so is
 * fetched no-cache (and cache-busted past the edge when `fresh`).
 *
 * The alias URL is built only after the TileJSON lookup settles: that lookup
 * is what fails the app over to the backup host, and the alias must follow.
 */
async function resolveCompanion(
  country: CameraTileCountry,
  pinned: (tileJson: CameraTileJson) => string | undefined,
  alias: (country: CameraTileCountry) => string,
  fresh?: boolean
): Promise<CompanionRequest> {
  const tileJson = await loadCameraTileJson(country);
  const pinnedUrl = tileJson ? pinned(tileJson) : undefined;
  if (pinnedUrl) return { url: pinnedUrl };
  const aliasUrl = alias(country);
  return { url: fresh ? bust(aliasUrl) : aliasUrl, init: { cache: 'no-cache' } };
}

/** Filter dictionary — a few KB per country. Generated by the tile pipeline
 *  from the same snapshot as that country's filter tileset; ids are
 *  build-scoped so the two are only valid as a matched pair.
 *
 *  `fresh: true` bypasses the module cache and, for alias documents, the CDN
 *  edge cache — used to recover when the cached manifest/tileset pair is
 *  skewed (alias edge entries for the two files can come from different
 *  hourly builds). Build-pinned documents cannot skew and are never busted. */
export async function loadCameraManifest(
  country: CameraTileCountry = 'us',
  opts?: { fresh?: boolean }
): Promise<CameraManifest> {
  if (!opts?.fresh) {
    const hit = cached.get(country);
    if (hit) return hit;
    const pending = inFlight.get(country);
    if (pending) return pending;
  }

  const promise = (async () => {
    try {
      const { url, init } = await resolveCompanion(
        country, (tj) => tj.manifest, cameraManifestUrl, opts?.fresh
      );
      const res = await fetch(url, init);
      if (!res.ok) throw new Error(`Manifest fetch failed: ${res.status}`);
      const data: unknown = await res.json();
      assertManifestShape(data);
      cached.set(country, data);
      return data;
    } finally {
      inFlight.delete(country);
    }
  })();
  if (!opts?.fresh) inFlight.set(country, promise);
  return promise;
}

/**
 * Verifies the filter tileset and manifest came from the same pipeline build.
 * The pipeline stamps the manifest's `version` (16-hex hash of the source
 * snapshot) into the filter tileset's TileJSON `name`. Returns:
 *  - 'match'    — stamp found and equals the manifest version
 *  - 'mismatch' — stamp found and differs (stale pair; filtering would be wrong)
 *  - 'unknown'  — no stamp / fetch failed (older tileset build; skip the check)
 */
export async function verifyFilterTilesetVersion(
  manifestVersion: string,
  country: CameraTileCountry = 'us',
  opts?: { fresh?: boolean }
): Promise<'match' | 'mismatch' | 'unknown'> {
  try {
    const { url, init } = await resolveCompanion(
      country, (tj) => tj.filter_tilejson, cameraFilterTileJsonUrl, opts?.fresh
    );
    const res = await fetch(url, init);
    if (!res.ok) return 'unknown';
    const tilejson: unknown = await res.json();
    const name = (tilejson as { name?: unknown }).name;
    if (typeof name !== 'string') return 'unknown';
    const stamp = name.match(/\b[0-9a-f]{16}\b/)?.[0];
    if (!stamp) return 'unknown';
    return stamp === manifestVersion ? 'match' : 'mismatch';
  } catch {
    return 'unknown';
  }
}

/** Test hook — not for app code. */
export function _resetManifestCacheForTests(): void {
  cached.clear();
  inFlight.clear();
}
